[package]
name = "sample_cargo"
version = "0.1.0"
authors = ["Bookman0001 <odonel51486666@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
